[package]
name = "mandy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
image = "0.24.6"
indicatif = "0.17.3"
ndarray = "0.15.6"
palette = "0.6.1"
